tangle-network/tangle

Cargo.lock, Cargo.toml, node/src/chain_spec/mod.rs, node/src/chain_spec/rococo.rs, pallets/collator-rewards/Cargo.toml, pallets/collator-rewards/src/lib.rs, pallets/collator-rewards/src/mock.rs, pallets/collator-rewards/src/tests.rs, runtime/rococo/Cargo.toml, runtime/rococo/src/impls.rs, runtime/rococo/src/lib.rs
A simple module for managing collator rewards. The collator rewards are initially paid out from the collator reward pot alloted at the time of genesis, every block `RewardAmount` is paid out to the block author along with the fees and tips. Once the initial genesis supply for collator rewards has been exhausted, the pallet will issue new amount of currency every block to continue rewarding the collators.
Closes #26
=> [TASK] Define collator rewards and inflation strategy

Cargo.lock, node/Cargo.toml, pallets/collator-rewards/Cargo.toml, runtime/rococo/Cargo.toml
Enable [try-runtime](https://docs.substrate.io/reference/command-line-tools/try-runtime/) builds
Part of #22
=> enable try-runtime builds

node/src/chain_spec/mod.rs, node/src/chain_spec/rococo.rs, runtime/rococo/src/lib.rs, runtime/rococo/src/protocol_substrate_config.rs, standalone/node/src/chain_spec.rs, standalone/runtime/src/lib.rs, standalone/runtime/src/protocol_substrate_config.rs
=> remove anchor and anchor handler pallets

docker/eggnet-collator.Dockerfile, docker/eggnet-standalone.Dockerfile
Changes introduced in this pr:
- Updated docker permissions
=> chore: update docker user permissions

pallets/collator-rewards/src/lib.rs, runtime/rococo/src/impls.rs
=> add collator reward event

Cargo.lock, scripts/run-standalone.sh, standalone/node/Cargo.toml, standalone/node/src/rpc.rs, standalone/runtime/src/protocol_substrate_config.rs
Closes #44 
Fix the chain type and change the chain ID
=>  Fix standalone rpc and chaintype 

Cargo.lock, node/src/chain_spec/mod.rs, node/src/chain_spec/rococo.rs, pallets/claims/Cargo.toml, pallets/claims/src/lib.rs, runtime/rococo/Cargo.toml, runtime/rococo/src/lib.rs, runtime/rococo/src/protocol_substrate_config.rs, standalone/node/src/chain_spec.rs, standalone/runtime/Cargo.toml, standalone/runtime/src/lib.rs, standalone/runtime/src/protocol_substrate_config.rs
Adds the claims pallet from Polkadot for claiming tokens.
=> Add claims pallet to runtimes

Cargo.lock, node/src/chain_spec/mod.rs, node/src/chain_spec/rococo.rs, pallets/claims/Cargo.toml, pallets/claims/src/lib.rs, runtime/rococo/src/lib.rs, standalone/node/src/chain_spec.rs, standalone/runtime/src/lib.rs
Return all "unclaimed" claims to a preset destination account from the Claims pallet.
=> return unclaimed funds to selected destination

Cargo.lock, node/src/chain_spec/mod.rs, node/src/chain_spec/rococo.rs, runtime/rococo/Cargo.toml, runtime/rococo/src/lib.rs, runtime/rococo/src/protocol_substrate_config.rs
This PR adds vanchor and vanchor-handler pallets to parachain runtime
=> add vanchor and vanchor-handler pallets to parachain

Cargo.lock, runtime/rococo/src/lib.rs, standalone/runtime/src/lib.rs
=> bump dkg-substrate & protocol-substrate deps

.github/workflows/checks.yml, Cargo.lock, README.md, node/Cargo.toml, node/src/command.rs, node/src/service.rs, pallets/claims/Cargo.toml, pallets/claims/src/lib.rs, pallets/parachain-staking/Cargo.toml, pallets/parachain-staking/src/lib.rs, pallets/parachain-staking/src/mock.rs, primitives/Cargo.toml, resources/testnet/README.MD, runtime/rococo/Cargo.toml, runtime/rococo/src/impls.rs, runtime/rococo/src/lib.rs, runtime/rococo/src/protocol_substrate_config.rs, runtime/rococo/src/weights/block_weights.rs, runtime/rococo/src/weights/extrinsic_weights.rs, runtime/rococo/src/weights/rocksdb_weights.rs, runtime/rococo/src/xcm_config.rs, scripts/README.md, scripts/polkadot-launch/README.md, standalone/node/Cargo.toml, standalone/node/src/benchmarking.rs, standalone/node/src/command.rs, standalone/node/src/service.rs, standalone/runtime/Cargo.toml, standalone/runtime/src/lib.rs, standalone/runtime/src/protocol_substrate_config.rs
Bumps all substrate deps to v0.9.30
Related to https://github.com/webb-tools/dkg-substrate/pull/443
=> bump to substrate-v0.9.30

Cargo.lock, primitives/src/lib.rs, runtime/rococo/src/lib.rs
Changelog:
- Switch to 1hr session
- Pull latest changes from dkg-substrate (https://github.com/webb-tools/dkg-substrate/pull/465, https://github.com/webb-tools/dkg-substrate/pull/464)
=> [fix] update dkg-substrate

Cargo.lock, node/src/cli.rs, node/src/command.rs, standalone/node/src/cli.rs, standalone/node/src/command.rs
Changelog:
- Add DkgKey subcommand to view local dkgkey files
- Depends on https://github.com/webb-tools/dkg-substrate/pull/469
=> add DKGKey subcommand

Cargo.lock, node/Cargo.toml, pallets/claims/Cargo.toml, pallets/parachain-staking/Cargo.toml, pallets/transaction-pause/Cargo.toml, primitives/Cargo.toml, runtime/rococo/Cargo.toml, runtime/rococo/src/lib.rs, standalone/node/Cargo.toml, standalone/runtime/src/lib.rs
Changelog:
- Pull latest changes from dkg-substrate
- Set version to `0.1.0` for all packages and set spec_version to `100`
=> Bump dkg-substrate and set unified package version

Cargo.lock, node/Cargo.toml, node/src/command.rs, node/src/service.rs
Changelog:
Refactor block import queue for nimbus consensus 
Resolves #122
=> [fix] refactor block import queue for nimbus

chainspecs/rococo/tangle-parachain-rococo.json
Update chainspec with new addresses
=> [fix] update rococo chainspec

Cargo.lock, node/Cargo.toml, runtime/rococo/Cargo.toml, runtime/rococo/src/lib.rs, standalone/runtime/Cargo.toml, standalone/runtime/src/lib.rs
Changelog:
Update dkg-substrate to latest release
=> [fix] Expose session period length

standalone/runtime/src/lib.rs
* bump dkg-substrate to v0.1.12
* reduce sessions per era
=> Reduce sessions per era (#141)

primitives/src/lib.rs, standalone/node/src/chain_spec.rs, standalone/node/src/command.rs, standalone/runtime/src/lib.rs
Refers Issue
https://github.com/webb-tools/relayer/issues/459
https://github.com/webb-tools/relayer/pull/462
=> Chain config for relayer testing

primitives/src/lib.rs
- Update block time to 3 sec
- Update session period to 10 blocks
=> Update session period and block time

standalone/node/src/chain_spec.rs
=> fix authority balance

.github/workflows/publish-release-binary.yml
=> [feat] add GH action to publish binary on release

Cargo.toml, pallets/claims/Cargo.toml, pallets/transaction-pause/Cargo.toml, primitives/Cargo.toml, standalone/node/Cargo.toml, standalone/runtime/Cargo.toml, taplo.toml
Changelog:
Adds taplo config file for toml formatting
Use `taplo fmt` to run
=> chore : add taplo config to formal toml files

flake.nix
Adds openssl to the build inputs in flakes.nix
=> Add openssl to the build inputs to nix flakes

Cargo.lock, Cargo.toml, standalone/node/Cargo.toml, standalone/node/src/cli.rs, standalone/node/src/command.rs, standalone/node/src/service.rs
Companion PR to https://github.com/webb-tools/dkg-substrate/pull/671
=> Add Relayer gadget to tangle

README.md, RELAYER.md
=> Add Running tangle with webb relayer docs

Cargo.lock, Cargo.toml, precompiles/precompile-registry/Cargo.toml, precompiles/precompile-registry/PrecompileRegistry.sol, precompiles/precompile-registry/src/lib.rs, precompiles/precompile-registry/src/mock.rs, precompiles/precompile-registry/src/tests.rs, standalone/runtime/Cargo.toml, standalone/runtime/src/precompiles.rs
=> Add precompile-registry

Cargo.toml, primitives/src/lib.rs, standalone/runtime/src/frontier_evm.rs, standalone/runtime/src/lib.rs
1. Added `rpc-binary-search-estimate` feature for `fc-rpc` which fixed the EVM Gas Estimation isues
2. Updated the constants
Closes #241
=> Fixing the EVM Fees (for real this time)

Cargo.lock, Cargo.toml, pallets/claims/Cargo.toml, pallets/claims/src/lib.rs, pallets/transaction-pause/Cargo.toml, pallets/transaction-pause/src/lib.rs, pallets/transaction-pause/src/mock.rs, precompiles/batch/src/mock.rs, precompiles/call-permit/src/mock.rs, precompiles/pallet-democracy/src/lib.rs, precompiles/pallet-democracy/src/mock.rs, precompiles/precompile-registry/src/mock.rs, precompiles/preimage/src/mock.rs, precompiles/proxy/src/mock.rs, precompiles/utils/tests-external/lib.rs, standalone/node/Cargo.toml, standalone/node/src/chain_spec.rs, standalone/node/src/command.rs, standalone/node/src/rpc/eth.rs, standalone/node/src/service.rs, standalone/runtime/Cargo.toml, standalone/runtime/src/lib.rs
=> Upgrade to substratev1.0.0

Cargo.lock, Cargo.toml, standalone/node/Cargo.toml, standalone/runtime/src/lib.rs
Borrowed from https://github.com/moonbeam-foundation/moonbeam/blob/fb741529e91b95a3a3ee4d8a30dd185554c93ff0/runtime/common/src/apis.rs#L274-L307
Requires both Runtime (WASM + Node) upgrade
=> Fix `gasEstimation` in fc-rpc runtime

.github/CODEOWNERS, .github/PULL_REQUEST_TEMPLATE.md, README.md
- Update contribution description
- Add code owners
=> Update readme doc and add code owners

Cargo.lock, Cargo.toml, standalone/node/Cargo.toml, standalone/node/src/chain_spec.rs
- Update Dkg to v0.4.3
- Update light client pallet to v0.4.3
Closes
=> Update dkg and light client to v0.4.3

Cargo.lock, Cargo.toml, light-client-configs/LIGHT-CLIENT.md, light-client-configs/block-relay-config.toml, light-client-configs/init-pallet-config.toml, standalone/node/Cargo.toml, standalone/node/src/cli.rs, standalone/node/src/command.rs, standalone/node/src/service.rs
- Update light client to 0.4.5 version
- Run light client relayer with tangle
- Add config
- Update readme
Closes
=> Run light client relayer with tangle

Cargo.lock, Cargo.toml, standalone/runtime/src/lib.rs
- Update dkg-substrate to latest version
=> chore: Update dkg to latest version

standalone/node/src/service.rs, standalone/node/src/signer_cli.rs, standalone/runtime/src/lib.rs
=> reduce tx fee and skip key checks in dev build

pallets/jobs/src/lib.rs, pallets/jobs/src/mock.rs, pallets/roles/src/impls.rs, pallets/roles/src/lib.rs, pallets/roles/src/mock.rs, pallets/roles/src/tests.rs, primitives/src/traits/jobs.rs, primitives/src/traits/roles.rs, primitives/src/types/roles.rs
=> feat: add roles metadata for validators

pallets/roles/src/impls.rs, pallets/roles/src/lib.rs, pallets/roles/src/mock.rs, pallets/roles/src/tests.rs, primitives/src/types/jobs.rs, primitives/src/types/roles.rs
=> Update role metadata structure and submit remove job request

node/src/distributions/mainnet.rs, node/src/distributions/testnet.rs, scripts/run-standalone-local.sh
=> fix startup script

pallets/zksaas/src/tests.rs, primitives/src/types/jobs.rs
- add `num_inputs` and `num_constraints` while creating a circuit.
Closes
=> Add more props to the zkSaaS circuit

Cargo.lock, Cargo.toml, primitives/Cargo.toml, primitives/src/verifier/mod.rs, runtime/testnet/Cargo.toml, runtime/testnet/src/lib.rs
- Adds Zk-SaaS pallet to Testnet Runtime
- Resolves @vutuanlinh2k2 issue while creating zkSaaS PhaseOne job.
Closes
=> Add ZkSaaS Pallet to Testnet Runtime

Cargo.lock, runtime/mainnet/src/lib.rs, runtime/testnet/src/lib.rs
- Add pallet proxy to testnet
- enable staking pallet to withdraw call. 
Closes #296
=> add pallet-proxy

scripts/run-standalone-local.sh
=> fix: update testnet script

node/src/command.rs, node/src/service.rs
=> Fix missing host function import issue

node/src/distributions/develop.rs
- Reduce The Claim Amount To Fix The PotUnderflow Error.
=> Reduce The Claim Amount To Fix The PotUnderflow Error

Cargo.lock, node/Cargo.toml, node/src/cli.rs, node/src/command.rs, node/src/lib.rs, node/src/main.rs, node/src/service.rs, node/src/utils.rs
- Restore the `auto-insert-keys` flag that previously existed
=> feat : re-introduce auto-insert-keys flag for babe

forge/.gitignore, forge/foundry.toml, forge/src/SigningRules.sol, forge/test/SigningRules.sol
- Restore signing rules contract
=> fix: restore signing rules contract

.github/workflows/publish-release-binary.yml, node/src/utils.rs
=> fix: Remove node-name and use randomly generated seed

Cargo.lock, Cargo.toml, runtime/mainnet/Cargo.toml, runtime/mainnet/src/lib.rs, runtime/testnet/Cargo.toml, runtime/testnet/src/lib.rs
- Adds multisig pallet
Closes #443
=> Add multisig pallet to both runtimes

README.md, pallets/roles/README.md
=> Add readme doc for roles pallet

Cargo.lock, Cargo.toml, pallets/dkg/Cargo.toml, pallets/dkg/src/lib.rs, pallets/dkg/src/misbehavior/dfns_cggmp21/aux_only.rs, pallets/dkg/src/misbehavior/dfns_cggmp21/integer.rs, pallets/dkg/src/misbehavior/dfns_cggmp21/mod.rs, pallets/dkg/src/misbehavior/dfns_cggmp21/tests.rs, pallets/dkg/src/misbehavior/dfns_cggmp21/zk/mod.rs, pallets/dkg/src/misbehavior/dfns_cggmp21/zk/ring_pedersen_parameters.rs, primitives/src/misbehavior/dfns_cggmp21.rs
- Adds on chain verifications for  N, s and t parameters
Part of #467
=> feat: `dfns/cggmp21` KeyRefresh `RingPedersenParams` on-chain verification

Cargo.lock, pallets/dkg/frost/Cargo.toml, pallets/dkg/frost/src/error.rs, pallets/dkg/frost/src/identifier.rs, pallets/dkg/frost/src/keys.rs, pallets/dkg/frost/src/lib.rs, pallets/dkg/frost/src/serialization.rs, pallets/dkg/frost/src/verifying_key.rs, pallets/dkg/src/functions.rs, pallets/dkg/src/lib.rs, pallets/dkg/src/signatures_schemes/schnorr_frost.rs, pallets/dkg/src/tests.rs, pallets/jobs/src/functions.rs, pallets/jobs/src/tests.rs, precompiles/staking/src/mock.rs, primitives/src/jobs/tss.rs
- Adds new logic for fixing frost signature verification
Closes
=> Fixes needed for frost DKG / threshold signatures to verify onchain.

flake.nix, pallets/dkg/src/lib.rs, pallets/dkg/src/misbehavior/dfns_cggmp21/aux_only.rs, pallets/dkg/src/misbehavior/dfns_cggmp21/integer.rs, pallets/dkg/src/misbehavior/dfns_cggmp21/keygen.rs, pallets/dkg/src/misbehavior/dfns_cggmp21/mod.rs, pallets/dkg/src/misbehavior/dfns_cggmp21/tests.rs, pallets/dkg/src/misbehavior/dfns_cggmp21/zk/mod.rs, pallets/dkg/src/misbehavior/dfns_cggmp21/zk/no_small_factor.rs, pallets/dkg/src/misbehavior/dfns_cggmp21/zk/paillier_blum_modulus.rs, primitives/src/misbehavior/dfns_cggmp21.rs
=> feat: Add `InvalidModProof` & `InvalidFacProof` on-chain verification

Cargo.toml
=> chore: Update pallet-eth2-light-client

pallets/jobs/src/lib.rs
- Reorders permitted caller check to be above any state changing functions.
Closes
=> Reorder: permitted caller check

pallets/jobs/src/functions.rs, pallets/jobs/src/mock.rs, pallets/jobs/src/tests.rs, pallets/roles/src/impls.rs, pallets/roles/src/lib.rs, pallets/roles/src/mock.rs, pallets/roles/src/tests.rs, pallets/roles/src/types.rs, precompiles/jobs/src/mock.rs, primitives/src/roles/traits.rs, runtime/mainnet/src/lib.rs, runtime/testnet/src/lib.rs
- Allow restaker to configure max active services for job, pallet limits already exists
=> feat: allow restaker to set max active jobs

pallets/roles/README.md
=> Update README.md, remove what's not used anymore

pallets/dkg/frost/frost-ed448/Cargo.toml
=> Fix std leak

Cargo.lock, Cargo.toml, pallets/dkg/frost/frost-ed448/Cargo.toml
=> fix gadget link

tangle-subxt/Cargo.toml
=> chore: remove unused crates in tangle-subxt

tangle-subxt/README.md, tangle-subxt/src/tangle_runtime.rs
- Adds `Clone`, `Eq` and `PartialEq` to the generated code.
- Updates README.
Closes
=> Add more derives to the generated code

pallets/dkg/src/signatures_schemes/ecdsa.rs
- Fixes stark curve ECDSA signature verification
Closes
=> Fix stark verification

.github/workflows/publish-docker.yml, .github/workflows/publish-release-binary.yml
=> ci: publish binary for testnet and mainnet

Cargo.lock, pallets/jobs/rpc/Cargo.toml, pallets/jobs/rpc/src/lib.rs
=> Fix testnet build

runtime/mainnet/src/filters.rs, runtime/testnet/src/filters.rs
=> Fix blocking calls in  filters

pallets/claims/src/lib.rs, pallets/claims/src/tests.rs
- Remove check of preexisting vesting in process_claim
=> allow multiple vesting schedules in claims

Cargo.lock, Cargo.toml, precompiles/balances-erc20/Cargo.toml, precompiles/balances-erc20/ERC20.sol, precompiles/balances-erc20/Permit.sol, precompiles/balances-erc20/src/eip2612.rs, precompiles/balances-erc20/src/lib.rs, precompiles/balances-erc20/src/mock.rs, precompiles/balances-erc20/src/tests.rs, runtime/mainnet/Cargo.toml, runtime/mainnet/src/precompiles.rs, runtime/testnet/Cargo.toml, runtime/testnet/src/precompiles.rs
- Adds balances-erc20 from Moonbeam to easily transfer from EVM.
Closes
=> Add balances-erc20 precompile

precompiles/balances-erc20/src/lib.rs, precompiles/balances-erc20/src/mock.rs, precompiles/balances-erc20/src/tests.rs
=> fix erc-20 precompile tests

pallets/jobs/src/functions.rs, pallets/jobs/src/lib.rs, pallets/roles/src/functions.rs, pallets/roles/src/lib.rs, pallets/roles/src/profile.rs, pallets/roles/src/tests.rs, pallets/staking/src/lib.rs, pallets/staking/src/tests.rs, precompiles/balances-erc20/src/lib.rs
- Remove all unsafe math
- Fix era duration calculation
- Compute total restake on restake
Closes #579
=> fix: Remove all unsafe math

Cargo.lock, Cargo.toml, node/src/mainnet_fixtures.rs, runtime/mainnet/src/lib.rs, runtime/testnet/src/lib.rs
- Update validator keys
- Release v0.6.6
=> update validators and release v0.6.6

tangle-subxt/src/test.rs
- Update rust test to submit DKGPhase2Results
You can use this script for testing events, validator reward and more.
Closes
=> Submit DKGPhase2Result through script

tangle-subxt/README.md
=> Update readme on running local tests

precompiles/jobs/Jobs.sol, precompiles/jobs/src/lib.rs, runtime/testnet/src/precompiles.rs
Jobs Precompile address : `0x0000000000000000000000000000000000000814`
Closes
=> Update Jobs precompile interface contract

forge/src/Jobs.sol, forge/src/SigningRules.sol, forge/test/SigningRules.sol, precompiles/jobs/src/lib.rs
=> Update signing rules contract

Cargo.lock, Cargo.toml, pallets/dkg/frost/frost-ed25519/Cargo.toml, pallets/dkg/frost/frost-ed448/Cargo.toml, pallets/dkg/frost/frost-p256/Cargo.toml, pallets/dkg/frost/frost-p384/Cargo.toml, pallets/dkg/frost/frost-redjubjub/Cargo.toml, pallets/dkg/frost/frost-ristretto255/Cargo.toml, pallets/dkg/frost/frost-secp256k1/Cargo.toml, pallets/dkg/frost/frost-taproot/Cargo.toml
- Makes sure to update main workspace version
Closes
=> Fix versioning, toml versioning

forge/src/hooks/RegisterationHook.sol, forge/src/hooks/RequestHook.sol, pallets/services/src/functions.rs, pallets/services/src/impls.rs, pallets/services/src/lib.rs, pallets/services/src/mock.rs, pallets/services/src/mock_evm.rs, pallets/services/src/traits.rs, precompiles/services/src/lib.rs, runtime/testnet/src/frontier_evm.rs, runtime/testnet/src/lib.rs
- Convert the used gas to weight so it can be used to pay fees.
- Allow the Runtime to execute EVM transactions for free, but the caller will pay that gas. 
Closes #638
=> feat: Add fees to the EVM hooks

Cargo.lock, flake.lock, node/src/rpc/mod.rs, pallets/services/Cargo.toml, pallets/services/rpc/runtime-api/src/lib.rs, pallets/services/rpc/src/lib.rs, pallets/services/src/functions.rs, pallets/services/src/impls.rs, pallets/services/src/lib.rs, pallets/services/src/mock.rs, pallets/services/src/rpc.rs, pallets/services/src/tests.rs, pallets/services/src/types.rs, primitives/Cargo.toml, primitives/src/jobs/v2.rs, primitives/src/jobs/v2/field.rs, runtime/testnet/src/lib.rs, runtime/testnet/src/tangle_services.rs
- Move Configurations to the runtime. Closes #648
- Allow for multiple sources for the same gadget binary. Closes #644 
Closes #644 
Closes #648
=> feat: Add Support for multi-sources to the gadgets and move constants to the runtime configuration

Cargo.lock, runtime/testnet/src/lib.rs
=> Adjust few runtime values for testnet

Cargo.lock, Cargo.toml, pallets/services/src/lib.rs, precompiles/verify-ecdsa-secp256k1-signature/Cargo.toml, precompiles/verify-ecdsa-secp256k1-signature/EcdsaSecp256k1.sol, precompiles/verify-ecdsa-secp256k1-signature/src/lib.rs, precompiles/verify-ecdsa-secp256k1-signature/src/mock.rs, precompiles/verify-ecdsa-secp256k1-signature/src/tests.rs, precompiles/verify-ecdsa-secp256r1-signature/Cargo.toml, precompiles/verify-ecdsa-secp256r1-signature/EcdsaSecp256r1.sol, precompiles/verify-ecdsa-secp256r1-signature/src/lib.rs, precompiles/verify-ecdsa-secp256r1-signature/src/mock.rs, precompiles/verify-ecdsa-secp256r1-signature/src/tests.rs, precompiles/verify-ecdsa-stark-signature/Cargo.toml, precompiles/verify-ecdsa-stark-signature/EcdsaStark.sol, precompiles/verify-ecdsa-stark-signature/src/lib.rs, precompiles/verify-ecdsa-stark-signature/src/mock.rs, precompiles/verify-ecdsa-stark-signature/src/tests.rs, runtime/testnet/Cargo.toml, runtime/testnet/src/lib.rs, runtime/testnet/src/precompiles.rs
=> Precompiles to verify Ecdsa signature

Cargo.lock, Cargo.toml, node/Cargo.toml, node/src/rpc/mod.rs
=> Add sygma pallet rpc

runtime/testnet/src/lib.rs, scripts/sygma-setup/setup.js, scripts/sygma-setup/util.js
=> Add PHA token to support Rhala

Cargo.lock
=> Split the error in sygma bridge pallet to identity the issue

runtime/mainnet/src/lib.rs, runtime/testnet/src/lib.rs
=> bump version to v1.0.9

Cargo.lock, runtime/testnet/src/lib.rs
=> Add deposit data parse logic for substrate as dest chain

Cargo.lock, Cargo.toml, runtime/mainnet/Cargo.toml, runtime/mainnet/src/lib.rs, runtime/testnet/Cargo.toml, runtime/testnet/src/lib.rs
=> add check metadata hash

precompiles/staking/src/lib.rs, precompiles/staking/src/mock.rs, precompiles/staking/src/tests.rs
- Fix account-id conversion bug in staking precompile
- Add nominator payout tests for different reward destinations
Closes
=> Fix account id conversion bug and add nominator payout tests

Cargo.lock, rust-toolchain.toml, scripts/sygma-setup/package-lock.json, scripts/sygma-setup/package.json
- 
Including a newer version of sygma pallets with some lib upgrade.
Closes
=> Sygma pallets upgrade

Cargo.lock, tangle-subxt/Cargo.toml, tangle-subxt/README.md, tangle-subxt/src/tangle_testnet_runtime.rs
- Adds serde support for some of the types.
- Updates README on how to generate the code.
Closes
=> Updates tangle-subxt codegen and its instructions.

Cargo.lock, flake.lock, flake.nix, tangle-subxt/Cargo.toml
- Update subxt-signer feature flags (enable `std` and `ecdsa`) 
Closes
=> Update subxt-signer features

Cargo.lock, Cargo.toml, precompiles/multi-asset-delegation/src/tests.rs, tangle-subxt/Cargo.toml, tangle-subxt/src/lib.rs
- Move `subxt/native` to `std` feature
- Bump tangle-subxt to 0.3.0
- Move dependencies to workspace
=> tangle-subxt: Fixup features

.github/workflows/publish-types.yml, types/scripts/updateMetadata.ts
- Update the release token to resolve the permission issue.
- Add a small `!` in the code to trigger the release.
Closes `NaN`
=> fix: Update Release Token To Fix Permission Issue

.github/workflows/publish-types.yml, types/package.json
- Update types package.json version to match with npm
Closes `NaN`
=> chore: Update types package.json version to match with npm

Cargo.lock, precompiles/balances-erc20/Cargo.toml, precompiles/balances-erc20/ERC20.sol, precompiles/balances-erc20/src/eip2612.rs, precompiles/balances-erc20/src/lib.rs, precompiles/balances-erc20/src/mock.rs, precompiles/balances-erc20/src/tests.rs
=> add transferNative to balances precompile

README.md
- Fixes the broken docs links in the README
Closes #808
=> chore: update doc links

.github/workflows/pre-release.yml
=> chore : generate pre-release on PR merge

.github/workflows/pre-release.yml
=> chore: use spider bot for releases

Cargo.lock, Cargo.toml, runtime/mainnet/src/lib.rs, runtime/testnet/src/lib.rs
=> chore: v1.2.8

Cargo.lock, Cargo.toml, runtime/mainnet/src/lib.rs, runtime/testnet/src/lib.rs
- Bump version to 1.2.9, based on commit https://github.com/tangle-network/tangle/commit/696322989f27a9aa4ec2bc7cc1bb634362a696b5
=> chore: v1.2.9

Cargo.lock, Cargo.toml, runtime/mainnet/src/lib.rs, runtime/testnet/src/lib.rs
=> chore: bump version to 1.2.10

Cargo.lock, Cargo.toml, README.md, RELAYER.md, deployment/docker-compose-archive.yml, deployment/docker-compose-validator.yml, docker/README.md, docker/docker-compose.yml, frost/frost-ed448/Cargo.toml, node/src/command.rs, node/tests/common/mod.rs, scripts/build-standalone-docker.sh
=> fix: remove webb-tools reference

runtime/mainnet/src/lib.rs, runtime/mainnet/src/migrations/mads_default_values_13032025.rs, runtime/mainnet/src/migrations/mod.rs, runtime/mainnet/src/migrations/session_key_migrations_08062024.rs, runtime/testnet/src/lib.rs
=> feat: add migrations for rewards pallet and fix session migration

pallets/services/src/tests/mod.rs, pallets/services/src/tests/type_checking.rs, primitives/src/services/field.rs
- Fixed `Field::Optional` type checking
- Added type checking tests
=> fix: optional field type checking

.github/workflows/publish-docker.yml, Dockerfile, docker/Tangle.Dockerfile
=> chore: fix docker build

Cargo.lock, Cargo.toml, node/src/command.rs, node/src/eth.rs, node/src/manual_seal.rs, node/src/service.rs
=> fix: remove NativeElseWasmExecutor and use wasm executor exclusively

Cargo.lock, Cargo.toml, node/Cargo.toml, node/src/blueprint_service.rs, node/src/lib.rs, node/src/main.rs, node/src/manual_seal.rs, node/src/service.rs, node/src/utils.rs
This pull request introduces the integration of a new feature called the "Blueprint Manager" into the project. The changes include updates to dependencies, the addition of new modules and functions to support the Blueprint Manager, and modifications to existing functions to accommodate the new feature.
* Updated `tokio` to version `1.44.2` in `Cargo.toml`.
* Added `blueprint-manager`, `blueprint-runner`, and `blueprint-keystore` dependencies in `Cargo.toml`.
* Added `blueprint_service.rs` to create and run the Blueprint Manager service.
* Added `blueprint_service` module in `lib.rs` and `main.rs`. [[1]](diffhunk://#diff-c1fa00b27f461be84b2e8f9f93974c238229bb7a87964886c0fe316ed825f4e0R1-R2) [[2]](diffhunk://#diff-d4320c54c71723c7049430272ce9c2854f11ec4c7512d203074f6b9 …
=> feat: integrate blueprint manager in tangle node

Cargo.lock
Update the SDK with the latest changes.
Closes
=> chore: update Blueprint SDK

Cargo.lock
- Update `blueprint-manager` to the latest commit
=> chore: update blueprint manager

Cargo.lock, node/src/blueprint_service.rs
=> chore: update blueprint manager for attestation support

pallets/credits/rpc/runtime-api/src/lib.rs
- clarify the comment in the credits RPC runtime API
- `git status --short`
=> Fix credits RPC comment

.github/workflows/claude-review.yml, .github/workflows/claude.yml
This pull request introduces two new GitHub Actions workflows to enhance automation in the repository. The first workflow automatically reviews pull requests using Claude, and the second enables Claude to respond to specific comments, reviews, and issues when mentioned. These changes aim to streamline code review processes and improve collaboration.
* **Auto Review PRs Workflow**:
- Added `.github/workflows/claude-review.yml` to automatically review pull requests that are opened or marked as ready for review (non-draft). The workflow uses the `anthropics/claude-code-action` to provide feedback on code quality, potential issues, performance, security, and documentation.
* **Claude GitHub Assistant Workflow**:
- Added …
=> chore: Add claude review and assistant
