standalone/runtime/src/lib.rs

This changes the ChainIdentifier of the standalone runtime to a value which is different than protocol_substrate's.

Update the standalone egg_net to an appropriate ChainIdentifier

---

Cargo.lock
README.md
node/Cargo.toml
node/src/command.rs
node/src/rpc.rs
polkadot-launch/README.md
runtime/Cargo.toml
runtime/src/lib.rs
runtime/src/protocol_substrate_config.rs
scripts/polkadot-launch/README.md
standalone/node/Cargo.toml
standalone/node/src/rpc.rs
standalone/runtime/Cargo.toml
standalone/runtime/src/lib.rs
standalone/runtime/src/protocol_substrate_config.rs

Depends on 
https://github.com/webb-tools/dkg-substrate/pull/318
https://github.com/webb-tools/protocol-substrate/pull/223
Bump substrate version to match Rococo

[chore] Bump substrate to 0.9.23

---

scripts/run-standalone.sh
standalone/runtime/src/protocol_substrate_config.rs

Fixing chain type to be `[2,0]` for standalone runtime and added script for running the standalone node

Fix chain type and script for running standalone node

---

runtime/rococo/src/lib.rs

~Resolves 44~
Add pallet_linkable_tree and pallet_mt rpc to rococo runtime.
Rpc already present in standalone runtime

[fix] add pallet_linkable_tree and pallet_mt rpc

---

docker/Tangle.Dockerfile

This fixes the following error with the recent docker images:
```
docker: Error response from daemon: OCI runtime create failed: container_linux.go:367: starting container process caused: exec: "${BINARY}": executable file not found in $PATH: unknown.
```

[Patch] Fix Docker build

---

primitives/src/lib.rs

it does not affect the actual result of the code, but more of easier readability in this case.

allow `clippy::identity_op` to avoid clippy warnings

---

node/src/chain_spec/mod.rs
node/src/chain_spec/rococo.rs

Changelog:
- Update to use 18 decimal places in chainspec, rest of the runtime already use 18

[fix] use 18 decimal places in chainspec

---

Cargo.lock
Cargo.toml

Changelog:
- Bump dkg-substrate to latest tag v0.1.11

Bump dkg-substrate and release v0.1.11

---

standalone/node/src/chain_spec.rs
standalone/runtime/src/protocol_substrate_config.rs

- rename the native asset from "WEBB" to "tTNT".
- add system propitiates to test chain specs.
- update `keygen_threshold = authorities.len()` by default.
- update `signature_threshold = (2 / 3) *  authorities.len()` by default.
- update `AdaptedBasicCurrency` to be the correct type.

Update Native Asset name and its Id

---

.github/workflows/publish-docker.yml
Cargo.lock
Cargo.toml
primitives/src/lib.rs
standalone/runtime/src/lib.rs

Changes:
- Set block time to 6secs for all feature-flags
- Bump dkg-substrate to v0.1.21
- Set proposal expiry as entire block session for integration tests
- Reduce Existential deposit by a factor of 10
- Remove parachain build from CI

Bump dkg-substrate to 0.1.21

---

flake.nix

This a small PR that fixes the issue of linking libgmp while using Nix to setup your local Env.

Fix libgmp Linking issue with nix setup.

---

.gitignore
Cargo.lock
flake.lock
flake.nix
rust-toolchain.toml

this updates flake.lock file to the new changes, since the rust-toolchain.toml got changed.

chore: Update flake deps

---

primitives/src/lib.rs
standalone/runtime/src/frontier_evm.rs

This makes EVM base fee a bit low, and also fixes the issue with #226 
The base fee is 0.1 GWei by default, and with no elasticity, which means we have a constant base fees, that's OKAY for now. A better option is to use a more dynamic base fee depends on the network conditions ..etc 
Reference: https://github.com/moonbeam-foundation/moonbeam/blob/61647d84124c8e6d099176ce5ba357f821204864/runtime/moonbeam/src/lib.rs#L403-L426

Update EVM Transaction Base Fee

---

Cargo.toml
standalone/node/src/cli.rs
standalone/node/src/command.rs
standalone/node/src/lib.rs
standalone/node/src/main.rs
standalone/node/src/signer_cli.rs

- CLI to sign data using authority wdkg key 
Output :
```
./target/debug/tangle-standalone dkg-signer --data test
Signature : Some(4cced2b27ac145e0512abad5756fe45c173c130c18c80bdf0017ba0416edc690261bf1780b00dd30209dff8e13ce8df22d0402311d610cdd921bdff3a6a51b0101)
```
Closes https://github.com/webb-tools/dkg-substrate/issues/717

CLI to sign data using authority wdkg key

---

Cargo.lock
pallets/roles/Cargo.toml
pallets/roles/src/impls.rs
pallets/roles/src/lib.rs
pallets/roles/src/mock.rs
pallets/roles/src/tests.rs
primitives/src/types/roles.rs
standalone/runtime/src/lib.rs

- The account should be a validator account
- User chooses to re-stake Full or Custom amount.
- Re-stake value should meet the minimum value requirement to opt for the role.
- The user can chill, unbound, and withdraw_unbound only when he has opted out of all the services and the role is cleared.
- `chill` , `unbound` , `withdraw_unbound` calls from staking-pallet are blocked and are only allowed through roles pallet
- The slashing part will be covered in separate PR.
Closes #291

Validator re-staking

---

precompiles/staking/StakingInterface.sol

- Updates `StakingInterface.sol` to include the following functions - `nominate`, `bond`, `bondExtra`, `unbond`, `withdrawUnbonded`, `chill`, `setPayee`, `setController`, `payoutStakers` and `rebond`.

Update staking interface contract

---

pallets/roles/src/impls.rs
pallets/roles/src/lib.rs
pallets/roles/src/mock.rs
pallets/roles/src/tests.rs

- User can select multiple roles
- User has a limit on re-staking (currently 50 % of total staked value)
-  Each role has a minimum re-stake requirement.
-  After assigning roles `RolestakingLedger` will be updated with the selected roles and staking record
---
```rust
pub type AccountRolesMapping<T: Config> = StorageMap<
_,
Blake2_256,
T::AccountId,
BoundedVec<RoleType, T::MaxRolesPerAccount>,
ValueQuery,
>;
```
```rust
#[scale_info(skip_type_params(T))]
pub struct RoleStakingLedger<T: Config> {
/// The stash account whose balance is actually locked and at stake.
pub stash: T::AccountId,
/// The total amount of the stash's balance that is re-staked for all selected roles.
/// This re-staked balance we are currently …
```

Support multiple roles

---

Cargo.lock
pallets/roles/src/impls.rs
pallets/roles/src/lib.rs
pallets/roles/src/mock.rs
pallets/roles/src/tests.rs
primitives/Cargo.toml
primitives/src/types/roles.rs

- Inflation rewards for mpc validators
Closes #301

Implement inflation rewards for mpc authorities

---

pallets/jobs/rpc/runtime-api/src/lib.rs
primitives/src/types/jobs.rs

This Runtime API is needed for gadgets, not for RPC as it exposes methods/read-only for the storage in the jobs pallet.
Closes #349

Update Jobs Runtime API

---

primitives/src/lib.rs
runtime/mainnet/src/lib.rs
runtime/testnet/src/lib.rs

- Move sesssion logic to babe pallet and remove fixed sessions
Closes #368

fix: Mainnet halts at block 100

---

node/src/chainspec/mainnet.rs
node/src/chainspec/testnet.rs
node/src/command.rs
node/src/distributions/develop.rs
node/src/distributions/mainnet.rs
node/src/distributions/mod.rs
primitives/src/lib.rs

- Add Option to run mainnet locally (for testing)
- Add Test accounts to claims
Closes #365

Testing claims on mainnet locally

---

Cargo.lock
Cargo.toml
node/Cargo.toml
node/src/chainspec/mainnet.rs
node/src/chainspec/testnet.rs
node/src/mainnet_fixtures.rs
node/src/testnet_fixtures.rs
pallets/dkg/Cargo.toml
pallets/dkg/src/tests.rs
pallets/jobs/Cargo.toml
pallets/jobs/src/mock.rs
pallets/roles/Cargo.toml
pallets/roles/src/impls.rs
pallets/roles/src/lib.rs
pallets/roles/src/mock.rs
pallets/roles/src/tests.rs
pallets/zksaas/Cargo.toml
precompiles/jobs/Cargo.toml
primitives/Cargo.toml
primitives/crypto/Cargo.toml
primitives/crypto/src/lib.rs
runtime/mainnet/Cargo.toml
runtime/testnet/Cargo.toml
runtime/testnet/src/lib.rs

- Adds role key to roles pallet
Closes #325

Add role key for roles pallet

---

node/src/eth.rs
node/src/rpc/mod.rs
node/src/service.rs
primitives/src/impls.rs
primitives/src/lib.rs
runtime/mainnet/src/frontier_evm.rs
runtime/mainnet/src/impls.rs
runtime/mainnet/src/lib.rs
runtime/testnet/src/frontier_evm.rs
runtime/testnet/src/impls.rs
runtime/testnet/src/lib.rs

- Combines common configs to primitives file
Closes #357

feat: Unify common runtime configs

---

node/src/command.rs

- Local Testnet and Live testnet uses now 4007 as chainid.
Closes #392

feat: Allocate 4007 for Tangle EVM testnet

---

node/src/chainspec/testnet.rs
node/src/distributions/develop.rs
pallets/claims/src/lib.rs

- Resolve the comment [here](https://github.com/webb-tools/tangle/pull/394#discussion_r1440735627).

Fix Wrapping Message Method

---

node/Cargo.toml
node/src/chainspec/mainnet.rs
node/src/chainspec/testnet.rs
primitives/src/lib.rs
runtime/mainnet/src/lib.rs
runtime/testnet/src/lib.rs

- Setup ss58 address prefix for testnet/mainnet
for mainnet, `5845` this would give us addresses with tg prefix for mainnet like `tgGmBRR5yM53bvq8tTzgsUirpPtfCXngYYU7uiihmWFJhmYGM`
for testnet,  `3799` this would give us addresses with  tt prefix for testnet like `ttFELSU4MTyzpfsgZ9tFinrmox7pV7nF1BLbfYjsu4rfDYM74`
TODO : If approved, update in ss58 registry
Closes #388

feat : set address prefixes

---

node/src/chainspec/mainnet.rs
node/src/chainspec/testnet.rs
node/src/distributions/develop.rs
node/src/distributions/mainnet.rs
pallets/claims/src/lib.rs
pallets/claims/src/tests.rs
pallets/claims/src/utils/ethereum_address.rs

- Update encoding for MultiAddress accounts (now we match over the type and only encode the inner value)
- Fix polkadotjs message format, by adding the prefix and suffix.
**Notes**
I did provide two examples for claims in both Native accounts and EVM accounts
- claim using EVM: https://gist.github.com/shekohex/6af3f02c3099bb031f8d952376904d9f
- claim using Native: https://gist.github.com/shekohex/8a1f3088a6df88275312bc30905c2ba0
cc @AtelyPham Lmk if you will need help integrating the new format. but the tl;dr is that we now do not need the codecPrefix (i.e `0x30313031`). Long version look into the [diff](https://gist.github.com/shekohex/6af3f02c3099bb031f8d952376904d9f/revisions#diff-161363d1881d5d13562032d6e060879a830a784cfa4 …

bugfix: Fix claims pallet

---

node/src/command.rs
primitives/src/lib.rs

- Update chain id for testnet: `3799`
- Update chain id for mainnet: `5845`
Closes

chore: update chain ids

---

pallets/jobs/src/functions.rs
pallets/jobs/src/lib.rs
pallets/jobs/src/mock.rs
pallets/roles/src/impls.rs
pallets/roles/src/lib.rs
pallets/roles/src/profile.rs
pallets/roles/src/tests.rs
precompiles/jobs/src/mock.rs
primitives/src/roles/traits.rs

Removed metadata part for now since it is just role key. We will need to figure out a good way to take additional metadata user input for multiple different role types. cc: @1xstj 
Closes #374

Store Role key while creating profile

---

README.md

Update README and remove outdated links

---

pallets/jobs/rpc/runtime-api/src/lib.rs
pallets/jobs/rpc/src/lib.rs
pallets/jobs/src/rpc.rs
pallets/jobs/src/tests.rs
primitives/src/jobs/mod.rs
runtime/testnet/src/lib.rs

fix : fix rpc result response and add tests

---

pallets/jobs/src/functions.rs
pallets/jobs/src/tests.rs

- Fixes the issue when we attempt to obtain phase one job data from the submitted jobs inside phase 2, which would initially fail since phase one is no longer present in the submitted jobs at this point and is only found in known outcomes.
Closes

bugfix: zkSaaS Phase2 submitted jobs not found

---

.github/workflows/publish-release-binary.yml

- Use older ubuntu version (v20) to build the release image, this will avoid the following errors on older systems
```
./tangle-testnet-linux-amd64: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.32' not found (required by ./tangle-testnet-linux-amd64)
./tangle-testnet-linux-amd64: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.34' not found (required by ./tangle-testnet-linux-amd64)
./tangle-testnet-linux-amd64: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.33' not found (required by ./tangle-testnet-linux-amd64)
```
For systems with older than ubuntu20, will have to build from source since github runners does not support those.

fix: use ubuntu20 to build release image

---

pallets/dkg/src/mock.rs
pallets/jobs/src/lib.rs
pallets/jobs/src/mock.rs
pallets/roles/src/benchmarking.rs
pallets/roles/src/impls.rs
pallets/roles/src/lib.rs
pallets/roles/src/mock.rs
pallets/roles/src/tests.rs
precompiles/jobs/src/mock.rs
precompiles/staking/src/lib.rs
precompiles/staking/src/tests.rs
primitives/src/jobs/mod.rs
primitives/src/roles/traits.rs
runtime/mainnet/src/lib.rs
runtime/testnet/src/lib.rs
types/src/interfaces/lookup.ts

- Rename `validators` in roles pallet to `restakers` 
- Make `MaxRestake` runtime config
Part of #466, split to seperate PR for easier review

fix: Roles pallet - rename validators to restakers

---

types/package.json

- Export the `types` properly on the `tangle-substrate-types`.
cc @1xstj, I may need your assistance in publishing the package to npm. Thank you!

fix: Added `types` properties to `package.json` file

---

node/src/chainspec/testnet.rs
precompiles/utils/src/precompile_set.rs
runtime/testnet/src/frontier_evm.rs
runtime/testnet/src/lib.rs
runtime/testnet/src/precompiles.rs

As precompiles are implemented inside the Runtime, they don't have a bytecode, and their account code is empty by default. 
However in Solidity calling a function of a contract often automatically adds a check that the contract bytecode is non-empty.
For that reason a dummy code (0x60006000fd) can be inserted at the precompile address to pass that check.
Closes

Make precompiles callable

---

pallets/dkg/src/functions.rs
pallets/dkg/src/signatures_schemes/ecdsa.rs
pallets/dkg/src/tests.rs
runtime/testnet/src/lib.rs

Following are changes made to store result with original message on chain 
- Instead of passing hashed messaged to `verify_ecdsa_signature` methods now will be passing original message which will be later hashed inside the function.
- Update `MaxSubmissionLen` to 60_000_000
```rust
pub fn verify_secp256k1_ecdsa_signature<T: Config>(
msg: &[u8],  // Original message bytes
signature: &[u8],
expected_key: &[u8],
derivation_path: &Option<BoundedVec<u8, T::MaxAdditionalParamsLen>>,
chain_code: Option<[u8; 32]>
) -> DispatchResult {
...
let signature = k256::ecdsa::Signature::from_slice(signature)
.map_err(|_| Error::<T>::InvalidSignatureDeserialization)?;
// Hash message here
let message = keccak_256(msg);
ensure!( …
```

Update ecdsa signature verification functions

---

Cargo.lock
Cargo.toml
precompiles/verify-bls381-signature/Bls381.sol
precompiles/verify-bls381-signature/Cargo.toml
precompiles/verify-bls381-signature/src/lib.rs
precompiles/verify-bls381-signature/src/mock.rs
precompiles/verify-bls381-signature/src/tests.rs
precompiles/verify-schnorr-signatures/Cargo.toml
precompiles/verify-schnorr-signatures/SchnorrSignatureVerifier.sol
precompiles/verify-schnorr-signatures/src/lib.rs
precompiles/verify-schnorr-signatures/src/mock.rs
precompiles/verify-schnorr-signatures/src/tests.rs
runtime/testnet/Cargo.toml
runtime/testnet/src/precompiles.rs

Precompiles to verify Schnorr and Bls381 Signatures

---

node/src/chainspec/testnet.rs
node/src/command.rs
primitives/src/lib.rs

- Update the local testnet chain id to be different from the live testnet chain id.

chore: update local ss58 prefix

---

Cargo.lock
tangle-subxt/Cargo.toml

- Published [tangle-subxt](https://crates.io/crates/tangle-subxt) to crates.io
- added [`@webb-tools/webb-devs`] team to it, so anyone in that team could publish new versions.
Closes

Publish Tangle subxt to crates.io

---

.config/nextest.toml
.github/workflows/checks.yml

- Before, `nextest` was being installed but never used. I set it up with their recommendations for CI: https://nexte.st/#features

Use nextest in CI

---

flake.nix
pallets/services/rpc/runtime-api/src/lib.rs
pallets/services/rpc/src/lib.rs
pallets/services/src/impls.rs
pallets/services/src/lib.rs
pallets/services/src/mock.rs
pallets/services/src/rpc.rs
pallets/services/src/tests.rs
pallets/services/src/types.rs
precompiles/services/Services.sol
precompiles/services/src/lib.rs
precompiles/services/src/mock.rs
precompiles/services/src/tests.rs
primitives/src/services/mod.rs
runtime/mainnet/src/lib.rs
runtime/mainnet/src/tangle_services.rs
runtime/testnet/src/lib.rs
runtime/testnet/src/tangle_services.rs

This pull request introduces support for adding assets in the services pallet by adding `AssetId` to various APIs and structures, and implementing constraints and validation for assets.
* Added `AssetId` to the `ServicesApi` trait and updated related method signatures in `pallets/services/rpc/runtime-api/src/lib.rs` and `pallets/services/rpc/src/lib.rs`. [[1]](diffhunk://#diff-04688388833aa6a1ce3103b4d232a243c3258a59dfe6554fd72048127bc8697bL30-R34) [[2]](diffhunk://#diff-04688388833aa6a1ce3103b4d232a243c3258a59dfe6554fd72048127bc8697bL44-R45) [[3]](diffhunk://#diff-5bf79853c5c7edd80d4b9c7f5f79603fe2acd7dd6cc813b0b5f75c7e0bf0c5feL39-R51) [[4]](diffhunk://#diff-5bf79853c5c7edd80d4b9c7f5f79603fe2acd7dd6cc813b0b5f75c7e0bf0c5feL66- …

feat!: Select Assets when requesting a service

---

scripts/run-standalone-local.sh

- In `scripts/run-standalone-local.sh`, check `$CARGO_TARGET_DIR` and fallback to `./target`

feat: check `$CARGO_TARGET_DIR` in `run-standalone-local.sh`

---

tangle-subxt/Cargo.toml

- Bump `tangle-subxt` to 0.5.0

chore: release `tangle-subxt` 0.5.0

---

Cargo.lock

- Fix the version of `tangle-subxt` in Cargo.lock
missed this in #806

chore: bump tangle-subxt in Cargo.lock

---

primitives/src/services/field.rs

- An optional field of any value other than `None` would fail type checking. Now it gets compared to `None` *or* the type of the optional.

fix: handle type checking for optionals

---

pallets/services/src/functions.rs
pallets/services/src/lib.rs
pallets/services/src/mock.rs
pallets/services/src/tests.rs
precompiles/services/src/lib.rs
primitives/src/services/mod.rs
primitives/src/types.rs

This pull request introduces several significant changes to the `pallets/services` module, focusing on enhancing the handling of ERC20 tokens, adding new error types, and implementing mechanisms for staging and refunding service payments. Key changes include modifications to the `erc20_transfer` function, the addition of new error types, and updates to the storage and event handling logic. Additionally, the pull request includes extensive updates to the testing framework to ensure the correctness of these new features.
* Modified the `erc20_transfer` function to accept `from` as an `H160` type instead of deriving it from the caller's account ID. This change simplifies the function and improves its flexibility.
* Added new …

feat: track pending payments to MBSM

---

precompiles/multi-asset-delegation/src/lib.rs

This pull request includes changes to the `precompiles/multi-asset-delegation/src/lib.rs` file, focusing on renaming methods to follow camelCase naming conventions.
Method renaming for camelCase consistency:
* Renamed `schedule_withdraw` to `scheduleWithdraw` (`precompiles/multi-asset-delegation/src/lib.rs`)
* Renamed `cancel_withdraw` to `cancelWithdraw` (`precompiles/multi-asset-delegation/src/lib.rs`)
* Renamed `schedule_delegator_unstake` to `scheduleDelegatorUnstake` (`precompiles/multi-asset-delegation/src/lib.rs`)
Closes

chore!: fix MAD Precompile function names

---

node/tests/evm_restaking.rs
precompiles/multi-asset-delegation/src/lib.rs
precompiles/multi-asset-delegation/src/tests.rs

Improvements to account ID handling:
* [`precompiles/multi-asset-delegation/src/lib.rs`](diffhunk://#diff-f83d645597140bef38b54c199f4274b6fb122158244eb292919e30f068108c5eL375-R375): Modified the conversion of the operator address to use `WrappedAccountId32` instead of the truncating and remapping.
Enhancements to test assertions:
* [`precompiles/multi-asset-delegation/src/tests.rs`](diffhunk://#diff-bd2c758e64b73a03dfae4acc1569505b0ee16bdbe79edbe5d015a13cce8f043bR263-R270): Added assertions in the `test_delegate_assets` function to verify that the correct delegation entries are present in the `Operators` storage.
Closes #881

fix: operator input in the MAD precompile `delegate` call

---

pallets/multi-asset-delegation/src/functions/evm.rs
pallets/multi-asset-delegation/src/functions/slash.rs
pallets/multi-asset-delegation/src/lib.rs

- When an ERC20 is slashed we don't know if it's from cross-chain restaking. Nonetheless, we call this fn.

feat: add slash alert for slashed erc20s

---

node/tests/evm_restaking.rs
pallets/services/rpc/runtime-api/src/lib.rs
pallets/services/rpc/src/lib.rs
pallets/services/src/rpc.rs
runtime/mainnet/src/lib.rs
runtime/testnet/src/lib.rs

feat: rpc to query pending services

---

types/package.json

- Manually bump `types` version in Github to address previous CI release failure due to outdated git history.
Closes `NaN`.

chore(types): Bump types to manual release v0.9.18

---

primitives/src/services/field.rs

- The encoding of structs isn't correct.
It's currently: `((string, type), ...)[]`
Should be: `(type, ...)`

fix: field struct encoding

---

node/src/blueprint_service.rs
node/src/manual_seal.rs
node/src/service.rs

This pull request introduces changes to the blueprint manager service and its initialization process to support a new `test_mode` parameter. The changes ensure that the blueprint manager can be configured differently based on the chain type.
Key changes include:
* Added a `test_mode` parameter to the `create_blueprint_manager_service` function in `node/src/blueprint_service.rs`. This parameter is used to configure the blueprint manager based on the chain type.
* Updated the `new_full` function in `node/src/manual_seal.rs` to pass the `test_mode` parameter when creating the blueprint manager service. The `test_mode` is determined based on the chain type. [[1]](diffhunk://#diff-bd5e4092850dbce14435fbf9909d500d6b21d17ddc7aa1a70c0 …

feat: Blueprint Manager Updates

---

Cargo.lock
node/src/blueprint_service.rs
node/src/cli.rs
node/src/command.rs
node/src/manual_seal.rs
node/src/service.rs
node/tests/common/mod.rs

- Tell the blueprint manager to run in test mode via the `--manager-test-mode` CLI flag, opposed to inferring it based on the chain type. More blueprint manager options should be exposed eventually, but this specifically is necessary for blueprints that have special test mode paths.

refactor: move blueprint manager test mode toggle to cli

---

Cargo.lock
tangle-subxt/Cargo.toml

- Update `tangle-subxt` to 0.16.0

chore: tangle-subxt 0.16.0

---

README.md
scripts/chopsticks.yml

doc: add guide to use chopsticks

---

.github/workflows/publish-subxt.yml

chore: add GA to publish tangle-subxt

---

node/src/rpc/mod.rs
primitives/src/lib.rs
primitives/src/types/rewards.rs
runtime/mainnet/src/lib.rs
runtime/testnet/src/lib.rs

fix: update credits rpc and constants

---

pallets/credits/src/mock.rs
pallets/credits/src/tests.rs
pallets/multi-asset-delegation/src/functions/delegate.rs
pallets/multi-asset-delegation/src/functions/deposit.rs
pallets/multi-asset-delegation/src/mock.rs
pallets/multi-asset-delegation/src/tests/delegate.rs
pallets/multi-asset-delegation/src/tests/deposit.rs
pallets/multi-asset-delegation/src/tests/native_restaking.rs
pallets/rewards/src/impls.rs
pallets/services/src/mock.rs
precompiles/multi-asset-delegation/src/mock.rs
precompiles/services/src/mock.rs
primitives/src/traits/rewards.rs

- Change credits awarded to on-delegate
Closes #1044

chore: change credits to on-delegate

---

pallets/multi-asset-delegation/src/functions/delegate.rs
pallets/multi-asset-delegation/src/tests/delegate.rs

fix: update process_schedule_delegator_unstake
